In [34]:
import torch
import torch.nn as nn
from torch.distributions.categorical import Categorical
from torch.distributions.normal import Normal
from torch.distributions.independent import Independent
from torch.optim import Adam
import numpy as np
import gym
from gym.spaces import Discrete, Box

### Categorical

In [35]:
asd = Categorical(probs=torch.tensor([0.10,0.90]))

In [36]:
print (asd.sample([100]))

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 0, 0])


In [41]:
torch.exp(asd.log_prob(torch.tensor([1,0,1,1,1,1,1,1,1])))

tensor([0.9000, 0.1000, 0.9000, 0.9000, 0.9000, 0.9000, 0.9000, 0.9000, 0.9000])

In [55]:
## Values are transformed using int(x). 0.01 -> 0 and 1.1 -> 1
torch.exp(asd.log_prob(torch.tensor([0.51,0.01,0.99, 1.01, 1.9]))) 

tensor([0.1000, 0.1000, 0.1000, 0.9000, 0.9000])

In [38]:
print (asd.batch_shape)

torch.Size([])


In [39]:
print (asd.event_shape)

torch.Size([])


### Normal

In [40]:
bsd = Normal(loc=torch.tensor([0.2,0.5]), scale=torch.tensor([100., 50.]))

In [9]:
print (bsd.sample())

tensor([-28.6104,  -9.7502])


In [10]:
print (bsd.event_shape, bsd.batch_shape)

torch.Size([]) torch.Size([2])


In [26]:
print (bsd.log_prob([[0.2,0.2],[2,3]]))

TypeError: rsub() received an invalid combination of arguments - got (Tensor, list), but expected one of:
 * (Tensor input, Tensor other, Number alpha)
 * (Tensor input, Number other, Number alpha)


In [11]:
csd = Independent(bsd, reinterpreted_batch_ndims=1)

In [12]:
print (csd.event_shape, csd.batch_shape)

torch.Size([2]) torch.Size([])


In [13]:
csd.sample()

tensor([89.2666, 32.6329])

In [ ]:
pr