In [6]:
import caffe
import numpy as np
from PIL import Image
import os

In [7]:
caffe.set_device(0)
caffe.set_mode_cpu()

In [8]:
net = caffe.Net('model/lenet.prototxt','model/lenet_iter_10000.caffemodel', caffe.TEST)

In [10]:
imgs = os.listdir('trainingSet/0/')
np100imgs = np.empty(shape=(100,1,28,28))

for i in range(100):
    readImage = Image.open(open('trainingSet/0/' + imgs[i]))
    np100imgs[i,0,:,:] = np.array(readImage)
    
net.blobs['data'].data[...] = np100imgs
_ = net.forward()

In [12]:
widthCell = 4 
heightCell = 4
stride = 1

def getCellsFromModel(net, widthCell, heightCell):
    for name, blob in net.blobs.iteritems(): # iterate through all the fm blobs
        if name in net.layer_dict.keys(): # Some blobs like 'data' do not have layers with same name
            if net.layer_dict[name].type == 'Convolution': # Looking for convolution blocks only
                #print ([x for x in net._layer_dict[name].blobs[0].shape])
                filters4d = net.layer_dict[name].blobs[0]
                filterNpData = filters4d.data
                print ("Processing {:<7}: FilterSize = {:<2} x {:<2} x {:<2} x {:<2} ".format (name, *[x for x in filters4d.shape]))
                print ("                       IFMSize = {:<3} x {:<3} x {:<3} x {:<3}".format(*[x for x in blob.shape]))
                stride = 1 # *** ASSUMPTION ***
                padEachSideX = filters4d.width / 2 
                padEachSideY = filters4d.height / 2

                paddedData = np.pad(blob.data,((0,0),(0,0), (padEachSideY,padEachSideY), (padEachSideX,padEachSideX)),'constant')
                print ("                Padded IFMSize = {:<3} x {:<3} x {:<3} x {:<3}".format(*paddedData.shape))
                # Iterate all Data
                for n in range(filters4d.num):
                    for c in range(filters4d.channels):
                        for h in range(0, paddedData.shape[2] - widthCell + 1):
                            for w in range(0, paddedData.shape[3]- widthCell + 1):
                                yield paddedData[n, c, h:h+heightCell, w:w+widthCell]
                                #yield (n,c,h,w)

In [14]:
asd = getCellsFromModel(net, 2, 2)
for i in range (100):
    print (asd.next())

Processing conv1  : FilterSize = 20 x 1  x 5  x 5  
                       IFMSize = 100 x 20  x 24  x 24 
                Padded IFMSize = 100 x 20  x 28  x 28 
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.          0.        ]
 [ 0.          0.04189505]]
[[ 0.          0.        ]
 [ 0.04189505  0.04189505]]
[[ 0.          0.        ]
 [ 0.04189505  0.13921404]]
[[ 0.          0.        ]
 [