In [14]:
from langchain.embeddings import HuggingFaceEmbeddings
import torch

In [5]:
model_name = "/home/ankdesh/.cache/huggingface/hub/models--bert-base-uncased/snapshots/1dbc166cf8765166998eff31ade2eb64c8a40076/"
model_kwargs = {'device': 'cpu'}
encode_kwargs = {'normalize_embeddings': False}
hf = HuggingFaceEmbeddings(
    model_name=model_name,
    model_kwargs=model_kwargs,
    encode_kwargs=encode_kwargs
)


No sentence-transformers model found with name /home/ankdesh/.cache/huggingface/hub/models--bert-base-uncased/snapshots/1dbc166cf8765166998eff31ade2eb64c8a40076/. Creating a new one with MEAN pooling.


In [8]:
from transformers import LlamaTokenizer, LlamaForCausalLM, pipeline
from transformers import AutoTokenizer, AutoModel
sentences = ["This is me", "A 2nd sentence"]
model_base_name = "/home/ankdesh/.cache/huggingface/hub/models--bert-base-uncased/snapshots/1dbc166cf8765166998eff31ade2eb64c8a40076/" # "meta-llama/Llama-2-7b-hf"
model = AutoModel.from_pretrained(model_base_name)
tokenizer = AutoTokenizer.from_pretrained(model_base_name)
feature_extraction = pipeline('feature-extraction', model=model, tokenizer=tokenizer)
embeddings = feature_extraction(sentences) # output should be of size (seq_len, embedding_dim) but is of size (seq_len, vocab_size)

In [12]:
print (len(embeddings[0][0][0]))

768


In [15]:
model(torch.IntTensor([tokenizer(sentences)['input_ids'][0]]),return_dict=True, output_hidden_states=True)['hidden_states']

(tensor([[[ 0.1686, -0.2858, -0.3261,  ..., -0.0276,  0.0383,  0.1640],
          [-0.6485,  0.6739, -0.0932,  ...,  0.4475,  0.6696,  0.1820],
          [-0.6270, -0.0633, -0.3143,  ...,  0.3427,  0.4636,  0.4594],
          [ 0.1365,  0.2253, -0.9982,  ...,  0.7263,  0.7519,  0.2361],
          [-0.3643, -0.1617,  0.0902,  ..., -0.1785,  0.1282, -0.0451]]],
        grad_fn=<NativeLayerNormBackward0>),
 tensor([[[ 0.1262,  0.0348, -0.0886,  ...,  0.0337,  0.1094,  0.0400],
          [ 0.0178,  0.3126,  0.1216,  ..., -0.0405,  0.7481,  0.0525],
          [-0.3870, -0.3250, -0.2099,  ...,  0.1536,  0.7361,  0.2984],
          [ 0.5721,  0.3080, -0.9041,  ...,  0.3541,  0.6504,  0.6652],
          [-0.0852, -0.0108,  0.0267,  ..., -0.2968,  0.5621,  0.1638]]],
        grad_fn=<NativeLayerNormBackward0>),
 tensor([[[ 0.0154, -0.2096, -0.2084,  ...,  0.1810,  0.1479,  0.0438],
          [ 0.1086,  0.6461,  0.5067,  ...,  0.2403,  0.7962, -0.0587],
          [-0.4878, -0.1401,  0.2317,  ...